#Author: Christopher Rico
#OSU ID: 933239746
#Date: 6/3/2018
#Description: Makefile for project 2

CC = gcc
CFLAGS = -g -w

STDCFILES = ftserve.c
#----------------------------------------------------------------------#

ftserver: ftserve.c
	${CC} ${CFLAGS} ${STDCFILES} -o ftserve

clean:
	rm -f ftserve
