all: program0_4 program0_1

program0_4: program0_4.cpp
	/usr/local/common/gcc-7.3.0/bin/g++ program0_4.cpp -o prog0_4 -O3 -lm -fopenmp

program0_1: program0_1.cpp
	/usr/local/common/gcc-7.3.0/bin/g++ program0_1.cpp -o prog0_1 -O3 -lm -fopenmp

clean:
	rm -f program0.o program0
